"""deleted user id

Revision ID: 497f87a13d74
Revises: 6b70552d0f77
Create Date: 2024-02-08 18:18:36.067826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497f87a13d74'
down_revision = '6b70552d0f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint('note_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('note_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
